cocktailProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ingredients/',include('ingredients.urls')),
    path('cocktails/',include('cocktails.urls')),
]

cocktails/urls.py
from django.urls import path
from .views import CocktailListView, CocktailDetailView, CocktailTabbed, CocktailIngredientOptions, EditCocktailView,DeleteCocktailView,ConfirmCocktailDeleteView
from ingredients.views import IngredientComponentListView

urlpatterns = [
    path('',CocktailListView.as_view(),name='cocktail-list'),
    path('ingredient-options/',CocktailIngredientOptions.as_view(),name='ingredient-options'),
    path('cocktail-tabbed/',CocktailTabbed.as_view(),name='cocktail-tabbed'),
    path('create/ingredient-search/',IngredientComponentListView.as_view(),name='cocktail-ingredient-search'),
    path("cocktail/<int:pk>/details/", CocktailDetailView.as_view(), name="cocktail-details"),
    path("cocktail/<int:pk>/edit/", EditCocktailView.as_view(), name="cocktail-edit"),
    path("confirm-cocktail-delete/<int:pk>/delete/", DeleteCocktailView.as_view(), name="cocktail-delete"),
    path("cocktail/<int:pk>/delete/", ConfirmCocktailDeleteView.as_view(), name="cocktail-confirm-delete"),
]

ingredients/urls.py
from django.urls import path
from .views import IngredientListView, IngredientDetailView, IngredientCreateView, IngredientEditView, ConfirmIngredientDeleteView, IngredientDeleteView

urlpatterns = [
    path('',IngredientListView.as_view(),name='ingredient-list'),
    path('details/<int:pk>/',IngredientDetailView.as_view(),name='ingredient-detail'),
    path('edit/<int:pk>/',IngredientEditView.as_view(),name='ingredient-edit'),
    path('delete/<int:pk>/',IngredientEditView.as_view(),name='ingredient-delete'),
    path('create/',IngredientCreateView.as_view(),name='ingredient-create'),
    path('delete_ingredient/<int:pk>/',IngredientDeleteView.as_view(),name='delete-ingredient'),
    path('confirm-ingredient-delete/<int:pk>/',ConfirmIngredientDeleteView.as_view(),name='confirm-ingredient-delete'),
]

ingredients/models.py
from django.db import models

# Create your models here.
class Ingredient(models.Model):
    TYPE_CHOICES = [
        ('spirit', 'Spirit'),
        ('modified_spirit', 'Modified Spirit'),
        ('citrus', 'Citrus'),
        ('bitters', 'Bitters'),
        ('liqueur', 'Liqueur'),
        ('sweetener', 'Sweetener'),
        ('fruit_puree', 'Fruit/Puree'),
        ('herb_spice', 'Herb/Spice'),
        ('garnish', 'Garnish'),
        ('dairy_cream', 'Dairy/Cream'),
        ('syrup_flavoring', 'Syrup/Flavoring'),
        ('vegetable', 'Vegetable'),
        ('wine_fortified_wine', 'Wine/Fortified Wine'),
        ('extract', 'Extract'),
        ('ice', 'Ice'),
    ]

    name = models.CharField(max_length=100)
    ingredient_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    brand = models.CharField(max_length=100, blank=True, null=True)
    abv = models.DecimalField("Alcohol by Volume (%)", max_digits=5, decimal_places=1, blank=True, null=True)
    sweetness = models.DecimalField("Sweetness (%)", max_digits=5, decimal_places=2, blank=True, null=True)
    acid = models.DecimalField("Acid (%)", max_digits=5, decimal_places=2, blank=True, null=True)
    instructions = models.TextField("How to create", blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

ingredients/forms.py
from django import forms
from .models import Ingredient

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name',
                  'ingredient_type',
                  'brand',
                  'abv',
                  'sweetness',
                  'acid',
                  'instructions']
        widgets = {
            'instructions': forms.Textarea(attrs={'rows': 4}),
        }

ingredients/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from ingredients.models import Ingredient
from .forms import IngredientForm

# Create your views here.
class IngredientListView(ListView):
    model = Ingredient
    context_object_name = 'ingredients'
    template_name = 'ingredients/ingredient_list.html'

    def get_queryset(self):
        # Sort the ingredients alphabetically by name
        return Ingredient.objects.all().order_by("name")

class IngredientComponentListView(ListView):
    model = Ingredient
    context_object_name = 'ingredients'
    template_name = 'ingredients/partials/cocktail_ingredient_search.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        field_id = self.request.GET.get('field_id')
        context['field_id'] = field_id
        return context
    
    def get_queryset(self):
        # Sort the ingredients alphabetically by name
        return Ingredient.objects.all().order_by("name")
    
class IngredientDetailView(DetailView):
    model = Ingredient
    context_object_name = 'ingredient'
    template_name = 'ingredients/ingredient_detail.html'
    
class IngredientCreateView(CreateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = 'ingredients/ingredient_create.html'
    success_url = reverse_lazy('ingredient-list')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'"{self.object.name}" successfully added.')
        return response
    
class IngredientEditView(UpdateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = 'ingredients/ingredient_create.html'
    success_url = reverse_lazy('ingredient-list')

class ConfirmIngredientDeleteView(DetailView):
    model = Ingredient
    context_object_name = 'ingredient'
    template_name = 'ingredients/partials/ingredient_confirm_delete.html'

class IngredientDeleteView(DeleteView):
    success_url = reverse_lazy('ingredient-list')

    def post(self, request, pk):
        ingredient = get_object_or_404(Ingredient, pk=pk)
        ingredient_name = ingredient.name  # Capture name for a more personalized message
        ingredient.delete()
        
        # Add a success message
        messages.success(request, f'"{ingredient_name}" successfully deleted.')
        
        return redirect(self.success_url)

ingredients/templates/ingredients/partials/cocktail_ingredient_search.html
{% load static %}

<div class="ingredient-search-comp">
    <!-- Search Bar at the Top -->
    <div class="form-group ingredient-search-header">
        <button class="modal-header__closeImg" data-dismiss="modal">
            <img src="{% static 'images/xmark-solid.svg'%}" alt="closeModal">
        </button>
        <h5>Add an ingredient</h5>
        <label for="searchCocktailIngredient" class="sr-only">Add an ingredient</label>
        <input id="searchCocktailIngredient" class="ingredient-search-input" type="text" name="searchCocktailIngredient" placeholder="Search..." data-popup="search">
    </div>

    <!-- Scrollable List of Ingredients -->
    <div class="select-ingredients-list">
        {% for ingredient in ingredients %}
                <button class="checkbox-container" 
                        data-ingredient-item-id="{{ ingredient.id }}" 
                        data-ingredient-item-name="{{ ingredient.name }}"
                        hx-on:click="populateIngredientField('{{ ingredient.name }}','{{ ingredient.id }}')">
                    <div class="checkbox-container__colOne">
                        <span class="cocktail-select-ingredient-name">{{ ingredient.name }}
                        </span>
                        <div class="cocktail-select-type-brand">
                            {% if ingredient.brand %}
                            <span class="cocktail-select-brand">{{ ingredient.brand}}</span>
                            <span> &#8226; </span>
                            {% endif %}
                            <span class="cocktail-select-type">{{ ingredient.get_ingredient_type_display }}</span>
                            {% if ingredient.abv %}
                            <span> &#8226; </span>
                            <span class="cocktail-select-ingredient-abv">{{ ingredient.abv }}%</span>
                            {% endif %}
                        </div>
                    </div>
                    <span class="item-select-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 144L48 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l144 0 0 144c0 17.7 14.3 32 32 32s32-14.3 32-32l0-144 144 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-144 0 0-144z"/></svg>
                    </span>
                </button>
        {% endfor %}
    </div>
</div>

<script>

</script>

<style>
    .select-ingredients-list {
        overflow-y: auto;
        max-height: 60vh;
        min-height: 60vh;
        
    }
    .ingredient-search-header {
        display: flex;
        flex-direction: column;
        gap:.5rem;
    }
    .modal-header__closeImg {
        align-self: flex-end;
    }
    .checkbox-container{
        display: flex;
        align-items: center;
        width: 100%;
        background-color: transparent;
        border: none;
        border-bottom: 1px solid #ced4da;
        padding: 1rem;
        color: var(--primaryColorBlack);
        cursor: pointer;
    }
    .checkbox-container:hover {
        background-color: rgba(0,0,0,.025);
        border-radius: .25rem;
    }
    .checkbox-container input {
        margin-left: auto;
    }
    .cocktail-select-ingredient-abv {
        font-weight: 400;
        color: #6c757d;
        font-size: .875rem;
    }

    .cocktail-select-ingredient-name {
        font-weight: 500;
    }
    .checkbox-container__colOne {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        width: 100%;
        gap: .5rem;
    }
    .cocktail-select-type-brand {
        color: #6c757d;
    }
    .cocktail-select-brand {
        font-style: italic;
        font-weight: 500;
        color: #6c757d;
        font-size: .875rem;
    }
    .cocktail-select-type {
        text-transform: capitalize;
        font-size: .875rem;
        color: #6c757d;
    }
    .select-ingredient-controls {
        margin-top: 1rem;
    }
    .item-select-icon svg {
        opacity: 0;
        width: .75rem;
        text-align: center;
        color:inherit;
        transition: opacity 75ms ease-in;
        }
    .checkbox-container:hover .item-select-icon > svg {
        opacity: 1;
    }

</style>

ingredients/templates/ingredients/partials/ingredient_confirm_delete.html
{% load static %}

<div class="modal-header">
    <button class="modal-header__closeImg">
        <img src="{% static 'images/xmark-solid.svg'%}" alt="closeModal">
    </button>
</div>
<form action="{% url 'delete-ingredient' pk=ingredient.id %}" method="POST">
    {% csrf_token %}

<div class="modal-body">
    <p>Are you sure you would like to remove this ingredient?</p> <p><strong>This action cannot be undone.</strong></p>
</div>
<div class="modal-footer">
    <button id="delete-modal-cancel" data-dismiss="modal" type="button" alt="closeModal" class="button button-secondary">Cancel</button>
    <button type="submit" class="button button-danger" >Confirm Delete</button>
</div>
</form>

<script>

</script>